concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  JAVA_DISTRO: temurin
  JAVA_VERSION: '8'
jobs:
  apidocs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: 17
    - continue-on-error: true
      name: Build JDK17+ required modules
      run: mvn -B -U -V clean install -DskipTests -pl :jersey-helidon-connector -am
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Build ApiDocs
      run: etc/scripts/apidocs.sh
    timeout-minutes: 30
  archetypes:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Test archetypes
      run: etc/scripts/test-archetypes.sh
    timeout-minutes: 45
  checkstyle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Checkstyle
      run: etc/scripts/checkstyle.sh
    - continue-on-error: true
      name: Upload checkstyle info
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle_results
        path: target/checkstyle/checkstyle-result.xml
        retention-days: 5
    timeout-minutes: 10
  copyright:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Copyright
      run: etc/scripts/copyright.sh
    - continue-on-error: true
      name: Upload copyright info
      uses: actions/upload-artifact@v4
      with:
        name: copyright_results
        path: copyright.log
        retention-days: 5
    timeout-minutes: 10
name: Validate
on:
  repository_dispatch:
    types: trigger-ga___validate.yml
